In [ ]:

from sklearn import datasets 
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.preprocessing import LabelEncoder

In [ ]:
from sklearn.neighbors import KNeighborsClassifier


In [ ]:
from sklearn.datasets import make_classification

X, y = make_classification(n_samples=1500, n_classes=2, n_features=15,random_state=4)
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2)


In [ ]:
X

array([[ 0.55606712,  0.81765035,  0.76559803, ..., -1.73464704,
        -1.44262363,  0.99802277],
       [-0.44292709, -0.1716115 , -0.20553915, ..., -0.28525576,
        -0.25561022,  1.35258003],
       [ 0.42480451,  0.49458434,  0.44234333, ..., -0.91390799,
        -0.5966444 , -0.04837957],
       ...,
       [-1.2291368 ,  1.3475153 , -0.59992223, ..., -0.22152118,
         0.04863582,  1.40420411],
       [-0.10660116, -0.84193976,  2.20661064, ...,  0.00262419,
        -0.73515266,  1.23891849],
       [ 0.17924064, -0.83157849, -0.94403015, ...,  1.28345539,
        -0.97279939, -2.26296263]])

In [ ]:
knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train,y_train)






KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=3, p=2,
                     weights='uniform')

In [ ]:
#predict prob for test data
prob = model.predict_proba(X_test)

#postive class prob get
probs = prob[:,1]

In [ ]:
prob1 = model1.predict_proba(X_test)
probs1 = prob1[:,1]

In [ ]:
iris = datasets.load_iris()
X = iris.data
y= iris.target

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2)

In [ ]:
ytest_pred = bagg_model.predict(X_test)
print(bagg_model.score(X_test,y_test))
print(confusion_matrix(y_test, ytest_pred))

0.9333333333333333
[[11  0  0]
 [ 0  9  2]
 [ 0  0  8]]


In [ ]:
from sklearn.model_selection import KFold 
from sklearn.model_selection import cross_val_score

In [ ]:
#dateset, crossvalication, #model
kfold = KFold(n_splits=10)
from numpy import mean
scores = cross_val_score(knn,X,y,scoring='accuracy',cv=kfold, n_jobs=-1)

In [ ]:
print('Accuracy:', (mean(scores)))

Accuracy: 0.9040000000000001


In [ ]:
def model():
  model = KNeighborsClassifier(n_neighbors=5)
  return model

def model_acc(cv):
  model1 = model()
  scores = cross_val_score(model1,X,y,scoring='accuracy', cv=cv,n_jobs=-1)
  return mean(scores), scores.min(), scores.max()


folds = range(3,40)
#min, max, mean value of accuracy at each fold
min,max, means = list(), list(), list()
#check for every k value
for k in folds:
  cv = KFold(n_splits=k, shuffle=True, random_state=1)
  k_mean, k_min, k_max = model_acc(cv)
  print('Fold=%d, accuracy=%.3f (%.3f,%.3f)',(k,k_mean,k_min,k_max))
  min.append(k_min)
  max.append(k_max)
  means.append(k_mean)



Fold=%d, accuracy=%.3f (%.3f,%.3f) (3, 0.9026666666666667, 0.884, 0.914)
Fold=%d, accuracy=%.3f (%.3f,%.3f) (4, 0.8966666666666667, 0.8693333333333333, 0.9226666666666666)
Fold=%d, accuracy=%.3f (%.3f,%.3f) (5, 0.9006666666666667, 0.8766666666666667, 0.9266666666666666)
Fold=%d, accuracy=%.3f (%.3f,%.3f) (6, 0.904, 0.872, 0.94)
Fold=%d, accuracy=%.3f (%.3f,%.3f) (7, 0.9039898158785356, 0.8598130841121495, 0.9392523364485982)
Fold=%d, accuracy=%.3f (%.3f,%.3f) (8, 0.9026268631243599, 0.8663101604278075, 0.9361702127659575)
Fold=%d, accuracy=%.3f (%.3f,%.3f) (9, 0.9052978380588222, 0.8614457831325302, 0.9520958083832335)
Fold=%d, accuracy=%.3f (%.3f,%.3f) (10, 0.906, 0.8666666666666667, 0.94)
Fold=%d, accuracy=%.3f (%.3f,%.3f) (11, 0.9020063234318279, 0.875, 0.9632352941176471)
Fold=%d, accuracy=%.3f (%.3f,%.3f) (12, 0.9046666666666666, 0.872, 0.96)
Fold=%d, accuracy=%.3f (%.3f,%.3f) (13, 0.9039960788836352, 0.8695652173913043, 0.9739130434782609)
Fold=%d, accuracy=%.3f (%.3f,%.3f) (14, 

In [ ]:
from sklearn import metrics

In [ ]:
#GridSearchCV
from sklearn.model_selection import GridSearchCV
#to choose best parameters for your model
#model = knn

params = {
        'n_neighbors' : [5,25,30,40],
        'weights': ['uniform','distance'],
        'algorithm': ['auto','ball_tree','kd_tree','brute'],
               
}
grid_knn = GridSearchCV(estimator=knn,
                       param_grid=params,
                        scoring='accuracy',cv=5,n_jobs=-1,verbose=1)
grid_knn.fit(X,y)
80

Fitting 5 folds for each of 32 candidates, totalling 160 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 2 concurrent workers.
[Parallel(n_jobs=-1)]: Done 128 tasks      | elapsed:    3.0s
[Parallel(n_jobs=-1)]: Done 160 out of 160 | elapsed:    3.3s finished


80

In [ ]:
ans = grid_knn.best_estimator_
ans

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=25, p=2,
                     weights='distance')

In [ ]:
grid_knn.best_score_

0.9306666666666666